spring:
  mvc:
    dispatch-options-request: true
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        
  # Cache Configuration  
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=12h