spring:
  mvc:
    dispatch-options-request: true
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    
# JWT configuration
jwt:
  secret: ${JWT_SECRET:defaultsecret}