ALTER TABLE `match` ADD `region` VARCHAR(255) NULL DEFAULT NULL AFTER `patch`, ADD `queue` VARCHAR(255) NULL DEFAULT NULL AFTER `region`;
ALTER TABLE `match` CHANGE `league_shard` `league_shard` INT(11) NOT NULL DEFAULT '3', CHANGE `game_type` `game_type` INT(11) NOT NULL DEFAULT '43';
ALTER TABLE `participant` CHANGE `lane` `lane_o` TINYINT(4) NULL DEFAULT NULL AFTER `id`, CHANGE `team` `team_o` TINYINT(4) NULL DEFAULT NULL AFTER `id`, CHANGE `rank` `rank_o` SMALLINT(6) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `participant` ADD `lane` VARCHAR(255) NULL DEFAULT NULL AFTER `id`, ADD `team` VARCHAR(255) NULL DEFAULT NULL AFTER `lane`, ADD `rank` VARCHAR(255) NULL DEFAULT NULL AFTER `team`;
ALTER TABLE `rank` CHANGE `game_type` `game_type` INT(11) NULL DEFAULT NULL FIRST, CHANGE `rank` `rank_o` INT(11) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `rank` ADD `queue` VARCHAR(255) NULL DEFAULT NULL AFTER `id`, ADD `rank` VARCHAR(255) NULL DEFAULT NULL AFTER `queue`;
ALTER TABLE `rank` CHANGE `game_type` `game_type` INT(11) NULL DEFAULT NULL AFTER `rank`;
ALTER TABLE `summoner` ADD `region` VARCHAR(255) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `league_of_legends_test`.`match` DROP INDEX `unique_game`, ADD UNIQUE `unique_game` (`game_id`, `region`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`participant` DROP INDEX `rank`, ADD INDEX `rank` (`rank`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`participant` DROP INDEX `lane`, ADD INDEX `lane` (`lane`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`participant` DROP INDEX `side`, ADD INDEX `side` (`team`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`participant` DROP INDEX `rank_2`, ADD INDEX `rank_2` (`rank`, `lp`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`participant` DROP INDEX `idx_champion_lane`, ADD INDEX `idx_champion_lane` (`champion`, `lane`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`participant` DROP INDEX `idx_summoner_champion_lane_match`, ADD INDEX `idx_summoner_champion_lane_match` (`summoner_id`, `champion`, `lane`, `match_id`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`participant` DROP INDEX `idx_summoner_champion_lane`, ADD INDEX `idx_summoner_champion_lane` (`summoner_id`, `champion`, `lane`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`rank` DROP INDEX `summoner_id`, ADD UNIQUE `summoner_id` (`summoner_id`, `queue`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`rank` DROP INDEX `game_type`, ADD INDEX `game_type` (`queue`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`summoner` DROP INDEX `unique_puuid_idx`, ADD UNIQUE `unique_puuid_idx` (`puuid`, `region`) USING BTREE;
ALTER TABLE `league_of_legends_test`.`summoner` DROP INDEX `unique_account_shard`, ADD UNIQUE `unique_account_shard` (`account_id`, `region`) USING BTREE;