CREATE TABLE `match` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `game_id` varchar(255) DEFAULT NULL,
 `queue` varchar(255) DEFAULT NULL,
 `region` varchar(255) DEFAULT NULL,
 `rank` varchar(255) DEFAULT NULL,
 `last_update` datetime NOT NULL DEFAULT current_timestamp(),
 `time_start` datetime(3) DEFAULT NULL,
 `time_end` datetime(3) DEFAULT NULL,
 `events` longtext DEFAULT '{}',
 `bans` longtext DEFAULT NULL,
 `patch` varchar(255) DEFAULT NULL,
 `patch_major` varchar(20) GENERATED ALWAYS AS (substring_index(`patch`,'.',2)) STORED,
 PRIMARY KEY (`id`),
 UNIQUE KEY `unique_game` (`game_id`,`region`) USING BTREE,
 KEY `time_start` (`time_start`,`time_end`),
 KEY `time_start_2` (`time_start`),
 KEY `queue` (`queue`),
 KEY `rank` (`rank`),
 KEY `patch_major` (`patch_major`),
 KEY `idx_match_queue_time` (`queue`,`time_start`,`id`),
 KEY `idx_m_filters` (`queue`,`rank`,`patch_major`,`id`),
 KEY `game_id` (`game_id`),
 KEY `idx_m_queue_patch` (`queue`,`patch_major`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1945327 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
