CREATE TABLE `participant` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `summoner_id` int(11) NOT NULL,
 `match_id` int(11) NOT NULL,
 `win` tinyint(1) NOT NULL,
 `kda` varchar(255) DEFAULT NULL,
 `champion` smallint(6) DEFAULT NULL,
 `level` tinyint(4) NOT NULL DEFAULT 0,
 `team` varchar(255) DEFAULT NULL,
 `lane` varchar(255) DEFAULT NULL,
 `role_quest_id` int(11) NOT NULL DEFAULT 0,
 `subteam` tinyint(4) NOT NULL DEFAULT 0,
 `subteam_placement` tinyint(4) NOT NULL DEFAULT 0,
 `rank` varchar(255) DEFAULT NULL,
 `lp` smallint(6) DEFAULT NULL,
 `gain` smallint(6) DEFAULT NULL,
 `damage` mediumint(9) NOT NULL DEFAULT 0,
 `doubles` tinyint(4) NOT NULL DEFAULT 0,
 `triples` tinyint(4) NOT NULL DEFAULT 0,
 `quadruples` tinyint(4) NOT NULL DEFAULT 0,
 `pentas` tinyint(4) NOT NULL DEFAULT 0,
 `q` smallint(6) NOT NULL DEFAULT 0,
 `w` smallint(6) NOT NULL DEFAULT 0,
 `e` smallint(6) NOT NULL DEFAULT 0,
 `r` smallint(6) NOT NULL DEFAULT 0,
 `d` smallint(6) NOT NULL DEFAULT 0,
 `f` smallint(6) NOT NULL DEFAULT 0,
 `damage_building` mediumint(9) NOT NULL DEFAULT 0,
 `healing` mediumint(9) NOT NULL DEFAULT 0,
 `cs` smallint(6) NOT NULL DEFAULT 0,
 `gold_earned` mediumint(9) DEFAULT NULL,
 `ward` smallint(6) DEFAULT NULL,
 `ward_killed` smallint(6) NOT NULL,
 `vision_score` smallint(6) DEFAULT NULL,
 `pings` longtext DEFAULT NULL,
 `build` longtext DEFAULT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `unique_game_analyzed_2` (`summoner_id`,`match_id`),
 KEY `participant_match_id_fkey` (`match_id`),
 KEY `champion` (`champion`),
 KEY `summoner_id` (`summoner_id`),
 KEY `idx_participant_covering` (`summoner_id`,`match_id`,`rank`,`lp`),
 KEY `idx_champion_lane_match` (`champion`,`lane`,`match_id`),
 KEY `idx_p_champion_lane_match` (`champion`,`lane`,`match_id`),
 KEY `idx_p_champion_match` (`champion`,`match_id`),
 CONSTRAINT `participant_match_id_fkey` FOREIGN KEY (`match_id`) REFERENCES `match` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `participant_summoner_id_fkey` FOREIGN KEY (`summoner_id`) REFERENCES `summoner` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=17183853 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
