CREATE TABLE `participant` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `summoner_id` int(11) NOT NULL,
 `match_id` int(11) NOT NULL,
 `win` tinyint(1) NOT NULL,
 `kda` varchar(191) NOT NULL DEFAULT '',
 `rank` int(11) NOT NULL,
 `lp` int(11) NOT NULL,
 `gain` int(11) NOT NULL,
 `champion` int(11) NOT NULL DEFAULT 0,
 `lane` int(11) DEFAULT NULL,
 `side` int(11) NOT NULL,
 `damage` mediumint(11) NOT NULL DEFAULT 0,
 `damage_building` mediumint(11) NOT NULL DEFAULT 0,
 `healing` mediumint(11) NOT NULL DEFAULT 0,
 `cs` smallint(11) NOT NULL DEFAULT 0,
 `ward` smallint(11) NOT NULL DEFAULT 0,
 `vision_score` smallint(11) NOT NULL DEFAULT 0,
 `build` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `unique_game_analyzed_2` (`summoner_id`,`match_id`),
 KEY `participant_match_id_fkey` (`match_id`),
 KEY `win` (`win`),
 KEY `lane` (`lane`),
 KEY `side` (`side`),
 KEY `champion` (`champion`),
 KEY `lp` (`lp`,`gain`,`champion`,`lane`),
 KEY `build` (`build`(768)),
 KEY `healing` (`healing`),
 KEY `damage` (`damage`),
 KEY `cs` (`cs`),
 KEY `ward` (`ward`),
 FULLTEXT KEY `build_2` (`build`),
 CONSTRAINT `participant_match_id_fkey` FOREIGN KEY (`match_id`) REFERENCES `match` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `participant_summoner_id_fkey` FOREIGN KEY (`summoner_id`) REFERENCES `summoner` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1122180 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci