CREATE TABLE `participant` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `summoner_id` int(11) NOT NULL,
 `match_id` int(11) NOT NULL,
 `win` tinyint(1) NOT NULL,
 `kda` varchar(191) NOT NULL DEFAULT '',
 `champion` smallint(6) DEFAULT NULL,
 `team` varchar(10) DEFAULT NULL,
 `lane` varchar(255) DEFAULT NULL,
 `subteam` tinyint(4) NOT NULL DEFAULT 0,
 `subteam_placement` tinyint(4) NOT NULL DEFAULT 0,
 `rank` varchar(255) DEFAULT NULL,
 `lp` smallint(6) DEFAULT NULL,
 `gain` smallint(6) DEFAULT NULL,
 `damage` mediumint(9) NOT NULL DEFAULT 0,
 `damage_building` mediumint(9) NOT NULL DEFAULT 0,
 `healing` mediumint(9) NOT NULL DEFAULT 0,
 `cs` smallint(6) NOT NULL DEFAULT 0,
 `gold_earned` mediumint(9) DEFAULT NULL,
 `ward` smallint(6) DEFAULT NULL,
 `ward_killed` smallint(6) NOT NULL,
 `vision_score` smallint(6) DEFAULT NULL,
 `pings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}',
 `build` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `unique_game_analyzed_2` (`summoner_id`,`match_id`),
 KEY `participant_match_id_fkey` (`match_id`),
 KEY `win` (`win`),
 KEY `champion` (`champion`),
 KEY `ward_killed` (`ward_killed`),
 KEY `lp` (`lp`),
 KEY `cs` (`cs`),
 KEY `rank` (`rank`) USING BTREE,
 KEY `lane` (`lane`) USING BTREE,
 KEY `side` (`team`) USING BTREE,
 KEY `rank_2` (`rank`,`lp`) USING BTREE,
 KEY `idx_champion_lane` (`champion`,`lane`) USING BTREE,
 KEY `idx_summoner_champion_lane_match` (`summoner_id`,`champion`,`lane`,`match_id`) USING BTREE,
 KEY `idx_summoner_champion_lane` (`summoner_id`,`champion`,`lane`) USING BTREE,
 KEY `idx_participant_summoner_lane_match_time` (`summoner_id`,`lane`,`match_id`),
 CONSTRAINT `participant_match_id_fkey` FOREIGN KEY (`match_id`) REFERENCES `match` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `participant_summoner_id_fkey` FOREIGN KEY (`summoner_id`) REFERENCES `summoner` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci